/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'expiresAt' : IDL.Int,
  'createdAt' : IDL.Int,
  'mediaKey' : IDL.Text,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'avatarKey' : IDL.Text,
});
export const CallSignal = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'callType' : IDL.Text,
  'callee' : IDL.Principal,
  'caller' : IDL.Principal,
  'payload' : IDL.Text,
  'signalType' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'videoId' : IDL.Text,
});
export const Duet = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'thumbnailKey' : IDL.Text,
  'createdAt' : IDL.Int,
  'caption' : IDL.Text,
  'originalVideoId' : IDL.Text,
  'videoKey' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'thumbnailKey' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'views' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'videoKey' : IDL.Text,
});
export const Match = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'conversationId' : IDL.Text,
});
export const StoryReaction = IDL.Record({
  'id' : IDL.Text,
  'storyId' : IDL.Text,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'emoji' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notifType' : IDL.Text,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'videoId' : IDL.Opt(IDL.Text),
});
export const FollowRequest = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'createdAt' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'imageKey' : IDL.Text,
  'caption' : IDL.Text,
});
export const StoryComment = IDL.Record({
  'id' : IDL.Text,
  'storyId' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
});
export const UserSettings = IDL.Record({
  'blockedUsers' : IDL.Text,
  'theme' : IDL.Text,
  'notificationsEnabled' : IDL.Bool,
  'dmPrivacy' : IDL.Text,
  'twoFactorEnabled' : IDL.Bool,
  'emailNotifications' : IDL.Bool,
  'showOnlineStatus' : IDL.Bool,
  'contentFilter' : IDL.Text,
  'videoQuality' : IDL.Text,
  'ageRestriction' : IDL.Bool,
  'language' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'muteNotificationSound' : IDL.Bool,
  'activityStatusVisible' : IDL.Bool,
  'pushNotifications' : IDL.Bool,
  'autoPlayVideos' : IDL.Bool,
  'readReceiptsEnabled' : IDL.Bool,
  'blockedHashtags' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptFollowRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addMessageReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPostComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addStoryComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addStoryReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelFollowRequest' : IDL.Func([IDL.Principal], [], []),
  'clearCallSignals' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'createDuet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'declineFollowRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDuet' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReelDraft' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteStory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteStoryComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteVideo' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'didCallerLike' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'didCallerLikePost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getActivityStatus' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallSignals' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(CallSignal)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateDetails' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'postCount' : IDL.Nat,
          'videoCount' : IDL.Nat,
          'mutualCount' : IDL.Nat,
          'followerCount' : IDL.Nat,
          'followingCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'lastMessageText' : IDL.Text,
            'lastMessageAt' : IDL.Int,
            'otherPrincipal' : IDL.Principal,
          })
        ),
      ],
      ['query'],
    ),
  'getCoverPhoto' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getDuetsByVideo' : IDL.Func([IDL.Text], [IDL.Vec(Duet)], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Video)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowingFeed' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(Video)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'username' : IDL.Text,
            'videoCount' : IDL.Nat,
            'totalViews' : IDL.Nat,
            'followerCount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getLikedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getMessageReactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Record({ 'sender' : IDL.Principal, 'emoji' : IDL.Text }))],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMutualFollowCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getMutualFollowProfiles' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getMyStoryReaction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StoryReaction)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingFollowRequests' : IDL.Func(
      [],
      [IDL.Vec(FollowRequest)],
      ['query'],
    ),
  'getPhotoPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getPinnedMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPinnedVideo' : IDL.Func([IDL.Principal], [IDL.Opt(Video)], ['query']),
  'getPopularFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Video)], ['query']),
  'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getPostComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getPostLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPotentialMatches' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getReelAnalytics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'shares' : IDL.Nat,
          'likes' : IDL.Nat,
          'saves' : IDL.Nat,
          'comments' : IDL.Nat,
          'plays' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReelDrafts' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'title' : IDL.Text,
            'thumbnailKey' : IDL.Text,
            'hashtags' : IDL.Text,
            'createdAt' : IDL.Int,
            'description' : IDL.Text,
            'videoKey' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getSavedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getStoriesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getStoryComments' : IDL.Func([IDL.Text], [IDL.Vec(StoryComment)], ['query']),
  'getStoryReactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StoryReaction)],
      ['query'],
    ),
  'getTrendingFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Video)], ['query']),
  'getTrendingHashtags' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'tag' : IDL.Text, 'count' : IDL.Nat }))],
      ['query'],
    ),
  'getUserDuets' : IDL.Func([IDL.Principal], [IDL.Vec(Duet)], ['query']),
  'getUserPhotos' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'getUserStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'videoCount' : IDL.Nat,
          'followerCount' : IDL.Nat,
          'followingCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserVideos' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
  'getVideoById' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
  'getViewedStoryIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'hasPendingFollowRequest' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'hasUnviewedStories' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'hideVideo' : IDL.Func([IDL.Text], [], []),
  'incrementView' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMatch' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isVideoSaved' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'pinMessage' : IDL.Func([IDL.Text], [], []),
  'pinVideo' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'postPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'postVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeStoryReaction' : IDL.Func([IDL.Text], [], []),
  'reportVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveReelDraft' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveVideo' : IDL.Func([IDL.Text], [], []),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'sendFollowRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'storeCallSignal' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'swipeLeft' : IDL.Func([IDL.Principal], [], []),
  'swipeRight' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unhideVideo' : IDL.Func([IDL.Text], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'unlikeVideo' : IDL.Func([IDL.Text], [], []),
  'unpinVideo' : IDL.Func([], [], []),
  'unsaveVideo' : IDL.Func([IDL.Text], [], []),
  'updateActivityStatus' : IDL.Func([IDL.Text], [], []),
  'updateCoverPhoto' : IDL.Func([IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUserSettings' : IDL.Func(
      [
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'viewStory' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'expiresAt' : IDL.Int,
    'createdAt' : IDL.Int,
    'mediaKey' : IDL.Text,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'avatarKey' : IDL.Text,
  });
  const CallSignal = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'callType' : IDL.Text,
    'callee' : IDL.Principal,
    'caller' : IDL.Principal,
    'payload' : IDL.Text,
    'signalType' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'videoId' : IDL.Text,
  });
  const Duet = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'thumbnailKey' : IDL.Text,
    'createdAt' : IDL.Int,
    'caption' : IDL.Text,
    'originalVideoId' : IDL.Text,
    'videoKey' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'thumbnailKey' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'views' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'videoKey' : IDL.Text,
  });
  const Match = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'conversationId' : IDL.Text,
  });
  const StoryReaction = IDL.Record({
    'id' : IDL.Text,
    'storyId' : IDL.Text,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'emoji' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notifType' : IDL.Text,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'videoId' : IDL.Opt(IDL.Text),
  });
  const FollowRequest = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'createdAt' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'imageKey' : IDL.Text,
    'caption' : IDL.Text,
  });
  const StoryComment = IDL.Record({
    'id' : IDL.Text,
    'storyId' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
  });
  const UserSettings = IDL.Record({
    'blockedUsers' : IDL.Text,
    'theme' : IDL.Text,
    'notificationsEnabled' : IDL.Bool,
    'dmPrivacy' : IDL.Text,
    'twoFactorEnabled' : IDL.Bool,
    'emailNotifications' : IDL.Bool,
    'showOnlineStatus' : IDL.Bool,
    'contentFilter' : IDL.Text,
    'videoQuality' : IDL.Text,
    'ageRestriction' : IDL.Bool,
    'language' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'muteNotificationSound' : IDL.Bool,
    'activityStatusVisible' : IDL.Bool,
    'pushNotifications' : IDL.Bool,
    'autoPlayVideos' : IDL.Bool,
    'readReceiptsEnabled' : IDL.Bool,
    'blockedHashtags' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptFollowRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addMessageReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPostComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addStoryComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addStoryReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelFollowRequest' : IDL.Func([IDL.Principal], [], []),
    'clearCallSignals' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'createDuet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'declineFollowRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDuet' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReelDraft' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteStory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteStoryComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteVideo' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'didCallerLike' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'didCallerLikePost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getActivityStatus' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallSignals' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(CallSignal)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateDetails' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'postCount' : IDL.Nat,
            'videoCount' : IDL.Nat,
            'mutualCount' : IDL.Nat,
            'followerCount' : IDL.Nat,
            'followingCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'lastMessageText' : IDL.Text,
              'lastMessageAt' : IDL.Int,
              'otherPrincipal' : IDL.Principal,
            })
          ),
        ],
        ['query'],
      ),
    'getCoverPhoto' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'getDuetsByVideo' : IDL.Func([IDL.Text], [IDL.Vec(Duet)], ['query']),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Video)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowingFeed' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'username' : IDL.Text,
              'videoCount' : IDL.Nat,
              'totalViews' : IDL.Nat,
              'followerCount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getLikedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getMessageReactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Record({ 'sender' : IDL.Principal, 'emoji' : IDL.Text }))],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getMutualFollowCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getMutualFollowProfiles' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getMyStoryReaction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StoryReaction)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingFollowRequests' : IDL.Func(
        [],
        [IDL.Vec(FollowRequest)],
        ['query'],
      ),
    'getPhotoPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getPinnedMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPinnedVideo' : IDL.Func([IDL.Principal], [IDL.Opt(Video)], ['query']),
    'getPopularFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getPostComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getPostLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPotentialMatches' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getReelAnalytics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'shares' : IDL.Nat,
            'likes' : IDL.Nat,
            'saves' : IDL.Nat,
            'comments' : IDL.Nat,
            'plays' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReelDrafts' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'title' : IDL.Text,
              'thumbnailKey' : IDL.Text,
              'hashtags' : IDL.Text,
              'createdAt' : IDL.Int,
              'description' : IDL.Text,
              'videoKey' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getSavedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getStoriesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'getStoryComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StoryComment)],
        ['query'],
      ),
    'getStoryReactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StoryReaction)],
        ['query'],
      ),
    'getTrendingFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'getTrendingHashtags' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'tag' : IDL.Text, 'count' : IDL.Nat }))],
        ['query'],
      ),
    'getUserDuets' : IDL.Func([IDL.Principal], [IDL.Vec(Duet)], ['query']),
    'getUserPhotos' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'getUserStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'videoCount' : IDL.Nat,
            'followerCount' : IDL.Nat,
            'followingCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserVideos' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
    'getVideoById' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
    'getViewedStoryIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'hasPendingFollowRequest' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'hasUnviewedStories' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'hideVideo' : IDL.Func([IDL.Text], [], []),
    'incrementView' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMatch' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isVideoSaved' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'pinMessage' : IDL.Func([IDL.Text], [], []),
    'pinVideo' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'postPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'postVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeStoryReaction' : IDL.Func([IDL.Text], [], []),
    'reportVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveReelDraft' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveVideo' : IDL.Func([IDL.Text], [], []),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'sendFollowRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'storeCallSignal' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'swipeLeft' : IDL.Func([IDL.Principal], [], []),
    'swipeRight' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unhideVideo' : IDL.Func([IDL.Text], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'unlikeVideo' : IDL.Func([IDL.Text], [], []),
    'unpinVideo' : IDL.Func([], [], []),
    'unsaveVideo' : IDL.Func([IDL.Text], [], []),
    'updateActivityStatus' : IDL.Func([IDL.Text], [], []),
    'updateCoverPhoto' : IDL.Func([IDL.Text], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateUserSettings' : IDL.Func(
        [
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'viewStory' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };