/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallSignal {
  'id' : string,
  'createdAt' : bigint,
  'callType' : string,
  'callee' : Principal,
  'caller' : Principal,
  'payload' : string,
  'signalType' : string,
}
export interface Comment {
  'id' : string,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'videoId' : string,
}
export interface Duet {
  'id' : string,
  'creator' : Principal,
  'thumbnailKey' : string,
  'createdAt' : bigint,
  'caption' : string,
  'originalVideoId' : string,
  'videoKey' : string,
}
export interface FollowRequest {
  'id' : string,
  'to' : Principal,
  'from' : Principal,
  'createdAt' : bigint,
}
export interface Match {
  'id' : string,
  'createdAt' : bigint,
  'user1' : Principal,
  'user2' : Principal,
}
export interface Message {
  'id' : string,
  'createdAt' : bigint,
  'text' : string,
  'sender' : Principal,
  'conversationId' : string,
}
export interface Notification {
  'id' : string,
  'notifType' : string,
  'createdAt' : bigint,
  'read' : boolean,
  'recipient' : Principal,
  'sender' : Principal,
  'videoId' : [] | [string],
}
export interface Post {
  'id' : string,
  'creator' : Principal,
  'hashtags' : Array<string>,
  'createdAt' : bigint,
  'imageKey' : string,
  'caption' : string,
}
export interface Story {
  'id' : string,
  'creator' : Principal,
  'expiresAt' : bigint,
  'createdAt' : bigint,
  'mediaKey' : string,
  'caption' : string,
  'mediaType' : string,
}
export interface StoryComment {
  'id' : string,
  'storyId' : string,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
}
export interface StoryReaction {
  'id' : string,
  'storyId' : string,
  'createdAt' : bigint,
  'user' : Principal,
  'emoji' : string,
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'username' : string,
  'createdAt' : bigint,
  'avatarKey' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'blockedUsers' : string,
  'theme' : string,
  'notificationsEnabled' : boolean,
  'dmPrivacy' : string,
  'twoFactorEnabled' : boolean,
  'emailNotifications' : boolean,
  'showOnlineStatus' : boolean,
  'contentFilter' : string,
  'videoQuality' : string,
  'ageRestriction' : boolean,
  'language' : string,
  'isPrivate' : boolean,
  'muteNotificationSound' : boolean,
  'activityStatusVisible' : boolean,
  'pushNotifications' : boolean,
  'autoPlayVideos' : boolean,
  'readReceiptsEnabled' : boolean,
  'blockedHashtags' : string,
}
export interface Video {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'thumbnailKey' : string,
  'hashtags' : Array<string>,
  'views' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'videoKey' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptFollowRequest' : ActorMethod<[string], boolean>,
  'addComment' : ActorMethod<[string, string], string>,
  'addMessageReaction' : ActorMethod<[string, string], undefined>,
  'addPostComment' : ActorMethod<[string, string], string>,
  'addStoryComment' : ActorMethod<[string, string], string>,
  'addStoryReaction' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelFollowRequest' : ActorMethod<[Principal], undefined>,
  'clearCallSignals' : ActorMethod<[Array<string>], undefined>,
  'createDuet' : ActorMethod<[string, string, string, string], string>,
  'createStory' : ActorMethod<[string, string, string], string>,
  'declineFollowRequest' : ActorMethod<[string], boolean>,
  'deleteComment' : ActorMethod<[string], boolean>,
  'deleteDuet' : ActorMethod<[string], boolean>,
  'deletePost' : ActorMethod<[string], boolean>,
  'deleteReelDraft' : ActorMethod<[string], boolean>,
  'deleteStory' : ActorMethod<[string], boolean>,
  'deleteStoryComment' : ActorMethod<[string], boolean>,
  'deleteVideo' : ActorMethod<[string], boolean>,
  'didCallerLike' : ActorMethod<[string], boolean>,
  'didCallerLikePost' : ActorMethod<[string], boolean>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getActivityStatus' : ActorMethod<[Principal], string>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallSignals' : ActorMethod<[[] | [Principal]], Array<CallSignal>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateDetails' : ActorMethod<
    [Principal],
    {
      'postCount' : bigint,
      'videoCount' : bigint,
      'mutualCount' : bigint,
      'followerCount' : bigint,
      'followingCount' : bigint,
    }
  >,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getConversations' : ActorMethod<
    [],
    Array<
      {
        'lastMessageText' : string,
        'lastMessageAt' : bigint,
        'otherPrincipal' : Principal,
      }
    >
  >,
  'getCoverPhoto' : ActorMethod<[Principal], [] | [string]>,
  'getDuetsByVideo' : ActorMethod<[string], Array<Duet>>,
  'getFeed' : ActorMethod<[bigint, bigint], Array<Video>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowingFeed' : ActorMethod<[Principal, bigint, bigint], Array<Video>>,
  'getLeaderboard' : ActorMethod<
    [],
    Array<
      {
        'principal' : Principal,
        'username' : string,
        'videoCount' : bigint,
        'totalViews' : bigint,
        'followerCount' : bigint,
      }
    >
  >,
  'getLikeCount' : ActorMethod<[string], bigint>,
  'getLikedVideos' : ActorMethod<[], Array<Video>>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getMessageReactions' : ActorMethod<
    [string],
    Array<{ 'sender' : Principal, 'emoji' : string }>
  >,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getMutualFollowCount' : ActorMethod<[Principal], bigint>,
  'getMutualFollowProfiles' : ActorMethod<[Principal], Array<UserProfile>>,
  'getMyStoryReaction' : ActorMethod<[string], [] | [StoryReaction]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingFollowRequests' : ActorMethod<[], Array<FollowRequest>>,
  'getPhotoPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getPinnedMessages' : ActorMethod<[Principal], Array<Message>>,
  'getPinnedVideo' : ActorMethod<[Principal], [] | [Video]>,
  'getPopularFeed' : ActorMethod<[bigint, bigint], Array<Video>>,
  'getPostById' : ActorMethod<[string], [] | [Post]>,
  'getPostComments' : ActorMethod<[string], Array<Comment>>,
  'getPostLikeCount' : ActorMethod<[string], bigint>,
  'getPotentialMatches' : ActorMethod<[], Array<UserProfile>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getReelAnalytics' : ActorMethod<
    [string],
    {
      'shares' : bigint,
      'likes' : bigint,
      'saves' : bigint,
      'comments' : bigint,
      'plays' : bigint,
    }
  >,
  'getReelDrafts' : ActorMethod<
    [],
    Array<
      {
        'id' : string,
        'title' : string,
        'thumbnailKey' : string,
        'hashtags' : string,
        'createdAt' : bigint,
        'description' : string,
        'videoKey' : string,
      }
    >
  >,
  'getSavedVideos' : ActorMethod<[], Array<Video>>,
  'getStoriesByUser' : ActorMethod<[Principal], Array<Story>>,
  'getStoryComments' : ActorMethod<[string], Array<StoryComment>>,
  'getStoryReactions' : ActorMethod<[string], Array<StoryReaction>>,
  'getTrendingFeed' : ActorMethod<[bigint, bigint], Array<Video>>,
  'getTrendingHashtags' : ActorMethod<
    [],
    Array<{ 'tag' : string, 'count' : bigint }>
  >,
  'getUserDuets' : ActorMethod<[Principal], Array<Duet>>,
  'getUserPhotos' : ActorMethod<[Principal], Array<Post>>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'getUserStats' : ActorMethod<
    [Principal],
    {
      'videoCount' : bigint,
      'followerCount' : bigint,
      'followingCount' : bigint,
    }
  >,
  'getUserVideos' : ActorMethod<[Principal], Array<Video>>,
  'getVideoById' : ActorMethod<[string], [] | [Video]>,
  'getViewedStoryIds' : ActorMethod<[], Array<string>>,
  'hasPendingFollowRequest' : ActorMethod<[Principal], boolean>,
  'hasUnviewedStories' : ActorMethod<[Principal], boolean>,
  'hideVideo' : ActorMethod<[string], undefined>,
  'incrementView' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMatch' : ActorMethod<[Principal], boolean>,
  'isVideoSaved' : ActorMethod<[string], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'likeVideo' : ActorMethod<[string], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'pinMessage' : ActorMethod<[string], undefined>,
  'pinVideo' : ActorMethod<[string], boolean>,
  'postPhoto' : ActorMethod<[string, string, Array<string>], string>,
  'postVideo' : ActorMethod<
    [string, string, Array<string>, string, string],
    string
  >,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'removeStoryReaction' : ActorMethod<[string], undefined>,
  'reportVideo' : ActorMethod<[string, string], undefined>,
  'saveReelDraft' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'saveVideo' : ActorMethod<[string], undefined>,
  'searchPosts' : ActorMethod<[string], Array<Post>>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'sendFollowRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], boolean>,
  'storeCallSignal' : ActorMethod<[Principal, string, string, string], string>,
  'swipeLeft' : ActorMethod<[Principal], undefined>,
  'swipeRight' : ActorMethod<[Principal], boolean>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unhideVideo' : ActorMethod<[string], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'unlikeVideo' : ActorMethod<[string], undefined>,
  'unpinVideo' : ActorMethod<[], undefined>,
  'unsaveVideo' : ActorMethod<[string], undefined>,
  'updateActivityStatus' : ActorMethod<[string], undefined>,
  'updateCoverPhoto' : ActorMethod<[string], undefined>,
  'updateProfile' : ActorMethod<[string, string, string], undefined>,
  'updateUserSettings' : ActorMethod<
    [
      boolean,
      boolean,
      string,
      string,
      string,
      boolean,
      string,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
      string,
      boolean,
      boolean,
      boolean,
      string,
      boolean,
    ],
    undefined
  >,
  'updateVideo' : ActorMethod<[string, string, string, Array<string>], boolean>,
  'viewStory' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];