/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: string;
    title: string;
    creator: Principal;
    thumbnailKey: string;
    hashtags: Array<string>;
    views: bigint;
    createdAt: bigint;
    description: string;
    videoKey: string;
}
export interface Duet {
    id: string;
    creator: Principal;
    thumbnailKey: string;
    createdAt: bigint;
    caption: string;
    originalVideoId: string;
    videoKey: string;
}
export interface Comment {
    id: string;
    createdAt: bigint;
    text: string;
    author: Principal;
    videoId: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Story {
    id: string;
    creator: Principal;
    expiresAt: bigint;
    createdAt: bigint;
    mediaKey: string;
    caption: string;
    mediaType: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Match {
    id: string;
    createdAt: bigint;
    user1: Principal;
    user2: Principal;
}
export interface CallSignal {
    id: string;
    createdAt: bigint;
    callType: string;
    callee: Principal;
    caller: Principal;
    payload: string;
    signalType: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface StoryComment {
    id: string;
    storyId: string;
    createdAt: bigint;
    text: string;
    author: Principal;
}
export interface Post {
    id: string;
    creator: Principal;
    hashtags: Array<string>;
    createdAt: bigint;
    imageKey: string;
    caption: string;
}
export interface Notification {
    id: string;
    notifType: string;
    createdAt: bigint;
    read: boolean;
    recipient: Principal;
    sender: Principal;
    videoId?: string;
}
export interface Message {
    id: string;
    createdAt: bigint;
    text: string;
    sender: Principal;
    conversationId: string;
}
export interface UserSettings {
    blockedUsers: string;
    theme: string;
    notificationsEnabled: boolean;
    dmPrivacy: string;
    twoFactorEnabled: boolean;
    emailNotifications: boolean;
    showOnlineStatus: boolean;
    contentFilter: string;
    videoQuality: string;
    ageRestriction: boolean;
    language: string;
    isPrivate: boolean;
    muteNotificationSound: boolean;
    activityStatusVisible: boolean;
    pushNotifications: boolean;
    autoPlayVideos: boolean;
    readReceiptsEnabled: boolean;
    blockedHashtags: string;
}
export interface FollowRequest {
    id: string;
    to: Principal;
    from: Principal;
    createdAt: bigint;
}
export interface StoryReaction {
    id: string;
    storyId: string;
    createdAt: bigint;
    user: Principal;
    emoji: string;
}
export interface UserProfile {
    bio: string;
    principal: Principal;
    username: string;
    createdAt: bigint;
    avatarKey: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptFollowRequest(requestId: string): Promise<boolean>;
    addComment(videoId: string, text: string): Promise<string>;
    addMessageReaction(messageId: string, emoji: string): Promise<void>;
    addPostComment(postId: string, text: string): Promise<string>;
    addStoryComment(storyId: string, text: string): Promise<string>;
    addStoryReaction(storyId: string, emoji: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelFollowRequest(target: Principal): Promise<void>;
    clearCallSignals(signalIds: Array<string>): Promise<void>;
    createDuet(originalVideoId: string, videoKey: string, thumbnailKey: string, caption: string): Promise<string>;
    createStory(mediaKey: string, mediaType: string, caption: string): Promise<string>;
    declineFollowRequest(requestId: string): Promise<boolean>;
    deleteComment(commentId: string): Promise<boolean>;
    deleteDuet(id: string): Promise<boolean>;
    deletePost(id: string): Promise<boolean>;
    deleteReelDraft(draftId: string): Promise<boolean>;
    deleteStory(id: string): Promise<boolean>;
    deleteStoryComment(commentId: string): Promise<boolean>;
    deleteVideo(id: string): Promise<boolean>;
    didCallerLike(videoId: string): Promise<boolean>;
    didCallerLikePost(postId: string): Promise<boolean>;
    followUser(target: Principal): Promise<void>;
    getActiveStories(): Promise<Array<Story>>;
    getActivityStatus(user: Principal): Promise<string>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallSignals(fromPrincipal: Principal | null): Promise<Array<CallSignal>>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidateDetails(target: Principal): Promise<{
        postCount: bigint;
        videoCount: bigint;
        mutualCount: bigint;
        followerCount: bigint;
        followingCount: bigint;
    }>;
    getComments(videoId: string): Promise<Array<Comment>>;
    getConversations(): Promise<Array<{
        lastMessageText: string;
        lastMessageAt: bigint;
        otherPrincipal: Principal;
    }>>;
    getCoverPhoto(p: Principal): Promise<string | null>;
    getDuetsByVideo(videoId: string): Promise<Array<Duet>>;
    getFeed(offset: bigint, limit: bigint): Promise<Array<Video>>;
    getFollowers(p: Principal): Promise<Array<Principal>>;
    getFollowing(p: Principal): Promise<Array<Principal>>;
    getFollowingFeed(p: Principal, offset: bigint, limit: bigint): Promise<Array<Video>>;
    getLeaderboard(): Promise<Array<{
        principal: Principal;
        username: string;
        videoCount: bigint;
        totalViews: bigint;
        followerCount: bigint;
    }>>;
    getLikeCount(videoId: string): Promise<bigint>;
    getLikedVideos(): Promise<Array<Video>>;
    getMatches(): Promise<Array<Match>>;
    getMessageReactions(messageId: string): Promise<Array<{
        sender: Principal;
        emoji: string;
    }>>;
    getMessages(other: Principal): Promise<Array<Message>>;
    getMutualFollowCount(other: Principal): Promise<bigint>;
    getMutualFollowProfiles(other: Principal): Promise<Array<UserProfile>>;
    getMyStoryReaction(storyId: string): Promise<StoryReaction | null>;
    getNotifications(): Promise<Array<Notification>>;
    getPendingFollowRequests(): Promise<Array<FollowRequest>>;
    getPhotoPosts(offset: bigint, limit: bigint): Promise<Array<Post>>;
    getPinnedMessages(otherPrincipal: Principal): Promise<Array<Message>>;
    getPinnedVideo(p: Principal): Promise<Video | null>;
    getPopularFeed(offset: bigint, limit: bigint): Promise<Array<Video>>;
    getPostById(id: string): Promise<Post | null>;
    getPostComments(postId: string): Promise<Array<Comment>>;
    getPostLikeCount(postId: string): Promise<bigint>;
    getPotentialMatches(): Promise<Array<UserProfile>>;
    getProfile(p: Principal): Promise<UserProfile | null>;
    getReelAnalytics(videoId: string): Promise<{
        shares: bigint;
        likes: bigint;
        saves: bigint;
        comments: bigint;
        plays: bigint;
    }>;
    getReelDrafts(): Promise<Array<{
        id: string;
        title: string;
        thumbnailKey: string;
        hashtags: string;
        createdAt: bigint;
        description: string;
        videoKey: string;
    }>>;
    getSavedVideos(): Promise<Array<Video>>;
    getStoriesByUser(p: Principal): Promise<Array<Story>>;
    getStoryComments(storyId: string): Promise<Array<StoryComment>>;
    getStoryReactions(storyId: string): Promise<Array<StoryReaction>>;
    getTrendingFeed(offset: bigint, limit: bigint): Promise<Array<Video>>;
    getTrendingHashtags(): Promise<Array<{
        tag: string;
        count: bigint;
    }>>;
    getUserDuets(p: Principal): Promise<Array<Duet>>;
    getUserPhotos(p: Principal): Promise<Array<Post>>;
    getUserSettings(): Promise<UserSettings>;
    getUserStats(p: Principal): Promise<{
        videoCount: bigint;
        followerCount: bigint;
        followingCount: bigint;
    }>;
    getUserVideos(p: Principal): Promise<Array<Video>>;
    getVideoById(id: string): Promise<Video | null>;
    getViewedStoryIds(): Promise<Array<string>>;
    hasPendingFollowRequest(target: Principal): Promise<boolean>;
    hasUnviewedStories(p: Principal): Promise<boolean>;
    hideVideo(videoId: string): Promise<void>;
    incrementView(id: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isMatch(other: Principal): Promise<boolean>;
    isVideoSaved(videoId: string): Promise<boolean>;
    likePost(postId: string): Promise<void>;
    likeVideo(videoId: string): Promise<void>;
    markNotificationsRead(): Promise<void>;
    pinMessage(messageId: string): Promise<void>;
    pinVideo(videoId: string): Promise<boolean>;
    postPhoto(imageKey: string, caption: string, hashtags: Array<string>): Promise<string>;
    postVideo(title: string, description: string, hashtags: Array<string>, videoKey: string, thumbnailKey: string): Promise<string>;
    registerUser(username: string, bio: string, avatarKey: string): Promise<void>;
    removeStoryReaction(storyId: string): Promise<void>;
    reportVideo(videoId: string, reason: string): Promise<void>;
    saveReelDraft(videoKey: string, thumbnailKey: string, title: string, description: string, hashtags: string): Promise<string>;
    saveVideo(videoId: string): Promise<void>;
    searchPosts(term: string): Promise<Array<Post>>;
    searchUsers(term: string): Promise<Array<UserProfile>>;
    searchVideos(term: string): Promise<Array<Video>>;
    sendFollowRequest(target: Principal): Promise<void>;
    sendMessage(recipient: Principal, text: string): Promise<boolean>;
    storeCallSignal(callee: Principal, signalType: string, payload: string, callType: string): Promise<string>;
    swipeLeft(target: Principal): Promise<void>;
    swipeRight(target: Principal): Promise<boolean>;
    unfollowUser(target: Principal): Promise<void>;
    unhideVideo(videoId: string): Promise<void>;
    unlikePost(postId: string): Promise<void>;
    unlikeVideo(videoId: string): Promise<void>;
    unpinVideo(): Promise<void>;
    unsaveVideo(videoId: string): Promise<void>;
    updateActivityStatus(status: string): Promise<void>;
    updateCoverPhoto(coverPhotoKey: string): Promise<void>;
    updateProfile(username: string, bio: string, avatarKey: string): Promise<void>;
    updateUserSettings(isPrivate: boolean, notificationsEnabled: boolean, theme: string, language: string, contentFilter: string, ageRestriction: boolean, blockedHashtags: string, blockedUsers: string, twoFactorEnabled: boolean, emailNotifications: boolean, pushNotifications: boolean, autoPlayVideos: boolean, videoQuality: string, activityStatusVisible: boolean, readReceiptsEnabled: boolean, muteNotificationSound: boolean, dmPrivacy: string, showOnlineStatus: boolean): Promise<void>;
    updateVideo(id: string, title: string, description: string, hashtags: Array<string>): Promise<boolean>;
    viewStory(id: string): Promise<void>;
}
import type { Notification as _Notification, Post as _Post, StoryReaction as _StoryReaction, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptFollowRequest(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFollowRequest(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addMessageReaction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessageReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessageReaction(arg0, arg1);
            return result;
        }
    }
    async addPostComment(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPostComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPostComment(arg0, arg1);
            return result;
        }
    }
    async addStoryComment(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addStoryComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStoryComment(arg0, arg1);
            return result;
        }
    }
    async addStoryReaction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStoryReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStoryReaction(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelFollowRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelFollowRequest(arg0);
            return result;
        }
    }
    async clearCallSignals(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCallSignals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCallSignals(arg0);
            return result;
        }
    }
    async createDuet(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDuet(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDuet(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createStory(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(arg0, arg1, arg2);
            return result;
        }
    }
    async declineFollowRequest(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.declineFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineFollowRequest(arg0);
            return result;
        }
    }
    async deleteComment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteDuet(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDuet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDuet(arg0);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteReelDraft(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReelDraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReelDraft(arg0);
            return result;
        }
    }
    async deleteStory(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStory(arg0);
            return result;
        }
    }
    async deleteStoryComment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStoryComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStoryComment(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async didCallerLike(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.didCallerLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.didCallerLike(arg0);
            return result;
        }
    }
    async didCallerLikePost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.didCallerLikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.didCallerLikePost(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getActiveStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStories();
            return result;
        }
    }
    async getActivityStatus(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityStatus(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallSignals(arg0: Principal | null): Promise<Array<CallSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallSignals(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallSignals(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateDetails(arg0: Principal): Promise<{
        postCount: bigint;
        videoCount: bigint;
        mutualCount: bigint;
        followerCount: bigint;
        followingCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateDetails(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateDetails(arg0);
            return result;
        }
    }
    async getComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConversations(): Promise<Array<{
        lastMessageText: string;
        lastMessageAt: bigint;
        otherPrincipal: Principal;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getCoverPhoto(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoverPhoto(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoverPhoto(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDuetsByVideo(arg0: string): Promise<Array<Duet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDuetsByVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDuetsByVideo(arg0);
            return result;
        }
    }
    async getFeed(arg0: bigint, arg1: bigint): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed(arg0, arg1);
            return result;
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getFollowingFeed(arg0: Principal, arg1: bigint, arg2: bigint): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingFeed(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingFeed(arg0, arg1, arg2);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<{
        principal: Principal;
        username: string;
        videoCount: bigint;
        totalViews: bigint;
        followerCount: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikeCount(arg0);
            return result;
        }
    }
    async getLikedVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikedVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikedVideos();
            return result;
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return result;
        }
    }
    async getMessageReactions(arg0: string): Promise<Array<{
        sender: Principal;
        emoji: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageReactions(arg0);
            return result;
        }
    }
    async getMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMutualFollowCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMutualFollowCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMutualFollowCount(arg0);
            return result;
        }
    }
    async getMutualFollowProfiles(arg0: Principal): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMutualFollowProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMutualFollowProfiles(arg0);
            return result;
        }
    }
    async getMyStoryReaction(arg0: string): Promise<StoryReaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStoryReaction(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStoryReaction(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingFollowRequests(): Promise<Array<FollowRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFollowRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFollowRequests();
            return result;
        }
    }
    async getPhotoPosts(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoPosts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoPosts(arg0, arg1);
            return result;
        }
    }
    async getPinnedMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedMessages(arg0);
            return result;
        }
    }
    async getPinnedVideo(arg0: Principal): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedVideo(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedVideo(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPopularFeed(arg0: bigint, arg1: bigint): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPopularFeed(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPopularFeed(arg0, arg1);
            return result;
        }
    }
    async getPostById(arg0: string): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostComments(arg0);
            return result;
        }
    }
    async getPostLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostLikeCount(arg0);
            return result;
        }
    }
    async getPotentialMatches(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPotentialMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPotentialMatches();
            return result;
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReelAnalytics(arg0: string): Promise<{
        shares: bigint;
        likes: bigint;
        saves: bigint;
        comments: bigint;
        plays: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelAnalytics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelAnalytics(arg0);
            return result;
        }
    }
    async getReelDrafts(): Promise<Array<{
        id: string;
        title: string;
        thumbnailKey: string;
        hashtags: string;
        createdAt: bigint;
        description: string;
        videoKey: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelDrafts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelDrafts();
            return result;
        }
    }
    async getSavedVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedVideos();
            return result;
        }
    }
    async getStoriesByUser(arg0: Principal): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoriesByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoriesByUser(arg0);
            return result;
        }
    }
    async getStoryComments(arg0: string): Promise<Array<StoryComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryComments(arg0);
            return result;
        }
    }
    async getStoryReactions(arg0: string): Promise<Array<StoryReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryReactions(arg0);
            return result;
        }
    }
    async getTrendingFeed(arg0: bigint, arg1: bigint): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingFeed(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingFeed(arg0, arg1);
            return result;
        }
    }
    async getTrendingHashtags(): Promise<Array<{
        tag: string;
        count: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingHashtags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingHashtags();
            return result;
        }
    }
    async getUserDuets(arg0: Principal): Promise<Array<Duet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDuets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDuets(arg0);
            return result;
        }
    }
    async getUserPhotos(arg0: Principal): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPhotos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPhotos(arg0);
            return result;
        }
    }
    async getUserSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return result;
        }
    }
    async getUserStats(arg0: Principal): Promise<{
        videoCount: bigint;
        followerCount: bigint;
        followingCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats(arg0);
            return result;
        }
    }
    async getUserVideos(arg0: Principal): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserVideos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserVideos(arg0);
            return result;
        }
    }
    async getVideoById(arg0: string): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getViewedStoryIds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getViewedStoryIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViewedStoryIds();
            return result;
        }
    }
    async hasPendingFollowRequest(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPendingFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPendingFollowRequest(arg0);
            return result;
        }
    }
    async hasUnviewedStories(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUnviewedStories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUnviewedStories(arg0);
            return result;
        }
    }
    async hideVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hideVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideVideo(arg0);
            return result;
        }
    }
    async incrementView(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementView(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isMatch(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMatch(arg0);
            return result;
        }
    }
    async isVideoSaved(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isVideoSaved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isVideoSaved(arg0);
            return result;
        }
    }
    async likePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likeVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeVideo(arg0);
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async pinMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinMessage(arg0);
            return result;
        }
    }
    async pinVideo(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.pinVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinVideo(arg0);
            return result;
        }
    }
    async postPhoto(arg0: string, arg1: string, arg2: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.postPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postPhoto(arg0, arg1, arg2);
            return result;
        }
    }
    async postVideo(arg0: string, arg1: string, arg2: Array<string>, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.postVideo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postVideo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async removeStoryReaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStoryReaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStoryReaction(arg0);
            return result;
        }
    }
    async reportVideo(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportVideo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportVideo(arg0, arg1);
            return result;
        }
    }
    async saveReelDraft(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReelDraft(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReelDraft(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVideo(arg0);
            return result;
        }
    }
    async searchPosts(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPosts(arg0);
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return result;
        }
    }
    async searchVideos(arg0: string): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return result;
        }
    }
    async sendFollowRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFollowRequest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async storeCallSignal(arg0: Principal, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.storeCallSignal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeCallSignal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async swipeLeft(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.swipeLeft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.swipeLeft(arg0);
            return result;
        }
    }
    async swipeRight(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.swipeRight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.swipeRight(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unhideVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unhideVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unhideVideo(arg0);
            return result;
        }
    }
    async unlikePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unlikeVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeVideo(arg0);
            return result;
        }
    }
    async unpinVideo(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinVideo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinVideo();
            return result;
        }
    }
    async unsaveVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveVideo(arg0);
            return result;
        }
    }
    async updateActivityStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivityStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivityStatus(arg0);
            return result;
        }
    }
    async updateCoverPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoverPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoverPhoto(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUserSettings(arg0: boolean, arg1: boolean, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: string, arg7: string, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: string, arg13: boolean, arg14: boolean, arg15: boolean, arg16: string, arg17: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
            return result;
        }
    }
    async updateVideo(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async viewStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.viewStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewStory(arg0);
            return result;
        }
    }
}
function from_candid_Notification_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoryReaction]): StoryReaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Video | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notifType: string;
    createdAt: bigint;
    read: boolean;
    recipient: Principal;
    sender: Principal;
    videoId: [] | [string];
}): {
    id: string;
    notifType: string;
    createdAt: bigint;
    read: boolean;
    recipient: Principal;
    sender: Principal;
    videoId?: string;
} {
    return {
        id: value.id,
        notifType: value.notifType,
        createdAt: value.createdAt,
        read: value.read,
        recipient: value.recipient,
        sender: value.sender,
        videoId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.videoId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n16(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
